language: node_js
node_js:
  - '0.11'
  - '0.10'
deploy:
  provider: npm
  email: jakob.mattsson@gmail.com
  skip_cleanup: true
  api_key:
    secure: cc5ddcaQY9ZojzR9aM9ur/IsCegNvgf+MNGOkstGxaPkC1VbYCAZ8w427SmlcJFUG4VWDqzreQHCc0mDBEO4MwDmBP6BgSfTNEfgZ039nJYsUcs/GySrPB67TKi/+ok8A8burpALCF9/VtusDoQkle0pWJbIj2QNC1dnF/F3fzY=
  on:
    node: '0.10'
    tags: true
notifications:
  hipchat:
    rooms:
      secure: nYtSyxbhJ6IM3ybexkfrIzq7JKckcEg4NjD8fQFYkaj9DGUfRluLk5p/DjzwskoSFWCEUiee6HF7jHjk2+wQ271LtSD8oFcSESGBMP5Zs9/nw9deVPMklW9F0CuHAqhKSjTHc5R+ILoP70bCUdxck2OF/N01IkErJb8+/ZE8Gvw=
